[functions]
external_node_modules = ["express"]
include_files = "src/**/*"

[build]
functions = "netlify/functions"
publish = "src"

[[redirects]]
from = "/"
to = "/netlify/functions/server"
status = 200
force = true

[[redirects]]
from = "/index"
to = "/netlify/functions/server"
status = 200
force = true

[[redirects]]
from = "/create"
to = "/netlify/functions/server"
status = 200
force = true

[[redirects]]
from = "/login"
to = "/netlify/functions/server"
status = 200
force = true

[[redirects]]
from = "/logout"
to = "/netlify/functions/server"
status = 200
force = true