[functions]
[funcitons.include_files]
external_node_modules = ["express"]
include_files = "src/**/*"

[build]
functions = "netlify/functions"
publish = "src"

[[redirects]]
from = "/"
to = "/.netlify/functions/index"
status = 200
force = true

[[redirects]]
from = "/index"
to = "/.netlify/functions/index"
status = 200
force = true

[[redirects]]
from = "/create"
to = "/.netlify/functions/index"
status = 200
force = true

[[redirects]]
from = "/login"
to = "/.netlify/functions/index"
status = 200
force = true

[[redirects]]
from = "/logout"
to = "/.netlify/functions/index"
status = 200
force = true